export const state = {
  commonIssues: [],
  commonIssueIndex: '',
  images: [],
  finding: '',
  equipment: '',
  playingSurface: '',
  standardsClause: '',
  probability: '',
  severity: '',
  comments: '',
  recommendations: '',
  menuAnchor: null,
  playingSurfaceMode: false,
}
