export const pageWidth = 760
export const pageHeight = 1080
export const verticalMargin = 12
export const pageMargin = 40
export const logoOffset = verticalMargin * 8.5
export const fontSize = 12
export const headerFontSize = 23
export const subHeaderFontSize = 16
export const blue = '#a4c2f4'
export const green = '#b6d7a8'
export const yellow = '#ffe599'
export const pink = '#ea9999'
export const purple = '#b4a7d6'
export const lightGray = '#d9d9d9'
