export const state = {
  navBarShadowEnabled: true,
  navColor: undefined,
  navTitle: null,
  leftNavComponent: null,
  rightNavComponent: null,
  bottomNavComponent: null,
  searchComponent: null,
  searchOnTop: true,
  snackbarOpen: false,
  snackbarAutoHideDuration: 2000,
  snackbarMessage: '',
  snackbarAction: null,
  unsubscribers: [],
}
